const config = require('./common/config/env.config.js');

const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const swaggerUi = require('swagger-ui-express');
const swaggerJSDoc = require('swagger-jsdoc');

//Load Documentation
const swaggerDefinition = {
    info: {
        title: 'Test API',
        version: '1.0.0',
        description: 'Test Express API with autogenerated swagger doc',
    },
    host: 'localhost:3600',
    basePath: '/api/v1'
};

const options = {
    swaggerDefinition,
    apis: ['./users/routes.*.js','./users/models/users.*.js'],
};

const swaggerSpec = swaggerJSDoc(options);

//Express router
const myRouter = express.Router();

//Load routes
const UsersRouter = require('./users/routes.config');
const AuthRouter = require('./security/routes.config');

app.use(bodyParser.json());
UsersRouter.routesConfig(myRouter);
AuthRouter.routesConfig(myRouter);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use('/api/v1',myRouter);

app.listen(config.port, function () {
    console.log('App is listening at port %s', config.port);
    console.log('You can access to documentation on localhost:%s/api-docs',config.port)
});