const config = require('./config/env.js');

const express = require('express');
const app = express();
var cors = require('cors');
const bodyParser = require('body-parser');
const swaggerUi = require('swagger-ui-express');
const swaggerJSDoc = require('swagger-jsdoc');
app.use(cors());
const swaggerDefinition = {
    swagger: "2.0",
    info: {
        title: 'Test API',
        version: '1.0.0',
        description: 'Test Express API with autogenerated swagger doc',
    },
    host: 'localhost:3600',
    basePath: '/api/v1',
    components: {
        securitySchemes: {
            bearerAuth: {
                type: 'http',
                scheme: 'bearer',
                bearerFormat: 'JWT'
            }
        }
    },
    securityDefinitions: {
        Bearer: {
            type: 'apiKey',
            name: 'Authorization',
            in: 'header'
        }
    }
    ,
    security: [{
        bearerAuth: []
    }]
};

const options = {
    swaggerDefinition,
    apis: ['./routes/routes.*.js','./models/*.model.js'],
};

const swaggerSpec = swaggerJSDoc(options);

//Express router
const myRouter = express.Router();

//Load routes
const UsersRouter = require('./routes/routes.users');
const ProjectsRouter = require('./routes/routes.projects');
const SprintsRouter = require('./routes/routes.sprints');
const TasksRouter = require('./routes/routes.tasks');
const AuthRouter = require('./routes/routes.auth');

app.use(bodyParser.json());
ProjectsRouter.routesConfig(myRouter);
SprintsRouter.routesConfig(myRouter);
TasksRouter.routesConfig(myRouter);
UsersRouter.routesConfig(myRouter);
AuthRouter.routesConfig(myRouter);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use('/api/v1',myRouter);
app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
});

app.listen(config.port, function () {
    console.log('App is listening at port localhost:%s', config.port);
    console.log('You can access to documentation on localhost:%s/api-docs',config.port)
});

module.exports = app;